#!/usr/bin/env bash
# Prevents committing generated files from the .conveyor-belt/ directory.
# These are generated during terraform plan/apply and should not be tracked.

set -euo pipefail

errors=0

for file in "$@"; do
  if [[ "$file" == .conveyor-belt/* ]] || [[ "$file" == */.conveyor-belt/* ]]; then
    echo "✗ Generated file should not be committed: ${file}"
    echo "  Add '.conveyor-belt/' to your .gitignore"
    errors=$((errors + 1))
  fi
done

if [ $errors -gt 0 ]; then
  echo ""
  echo "Found ${errors} generated file(s) staged for commit."
  echo "The .conveyor-belt/ directory is generated by 'terraform plan' and should be in .gitignore."
  exit 1
fi
