# frozen_string_literal: true

# Auto-generated by: ruby scripts/list_routes.rb --ruby-output customer
# Do not edit manually - regenerate with `scripts/list_routes.rb --ruby-output customer'

module Routes
  CUSTOMER = [
    {
      verb: "POST",
      path: "/account_balance/withdraw",
      gateway: "customer",
      lambda: "customer",
      controller: "account_balance",
      action: "withdraw",
      auth: "cognito",
      tables: [:customers, :action_logs]
    },
    {
      verb: "POST",
      path: "/account_members/invite",
      gateway: "customer",
      lambda: "customer",
      controller: "account_members",
      action: "invite",
      auth: "cognito",
      tables: [:account_members, :customers]
    },
    {
      verb: "GET",
      path: "/billing/my-bill",
      gateway: "customer",
      lambda: "customer",
      controller: "billing",
      action: "my_bill",
      auth: "cognito",
      tables: [:inventory, :customers, :containers, :billing_events]
    },
    {
      verb: "POST",
      path: "/billing/update-payment-method",
      gateway: "customer",
      lambda: "customer",
      controller: "billing",
      action: "update_payment_method",
      auth: "cognito",
      tables: [:customers]
    },
    {
      verb: "POST",
      path: "/connect_account/dashboard-link",
      gateway: "customer",
      lambda: "customer",
      controller: "connect_account",
      action: "dashboard_link",
      auth: "cognito",
      tables: [:customers]
    },
    {
      verb: "POST",
      path: "/connect_account/onboarding-link",
      gateway: "customer",
      lambda: "customer",
      controller: "connect_account",
      action: "onboarding_link",
      auth: "cognito",
      tables: [:customers]
    },
    {
      verb: "POST",
      path: "/connect_account/refresh",
      gateway: "customer",
      lambda: "customer",
      controller: "connect_account",
      action: "refresh",
      auth: "cognito",
      tables: [:customers]
    },
    {
      verb: "GET",
      path: "/containers/search",
      gateway: "customer",
      lambda: "customer",
      controller: "containers",
      action: "search",
      auth: "cognito",
      tables: [:containers, :inventory]
    },
    {
      verb: "GET",
      path: "/dashboard/summary",
      gateway: "customer",
      lambda: "customer",
      controller: "dashboard",
      action: "summary",
      auth: "cognito",
      tables: [:inventory, :customers, :pickups, :account_members]
    },
    {
      verb: "POST",
      path: "/items/abandon-bulk",
      gateway: "customer",
      lambda: "customer",
      controller: "items",
      action: "abandon_bulk",
      auth: "cognito",
      tables: [:inventory, :containers, :item_changes, :item_listings]
    },
    {
      verb: "GET",
      path: "/items/abandoned",
      gateway: "customer",
      lambda: "customer",
      controller: "items",
      action: "abandoned",
      auth: "cognito",
      tables: [:inventory, :containers, :item_changes, :item_listings]
    },
    {
      verb: "POST",
      path: "/items/bulk-list-for-sale",
      gateway: "customer",
      lambda: "customer",
      controller: "items",
      action: "bulk_list_for_sale",
      auth: "cognito",
      tables: [:inventory, :containers, :item_changes, :item_listings]
    },
    {
      verb: "GET",
      path: "/items/missing-complements",
      gateway: "customer",
      lambda: "customer",
      controller: "items",
      action: "missing_complements",
      auth: "cognito",
      tables: [:inventory, :containers, :item_changes, :item_listings]
    },
    {
      verb: "GET",
      path: "/items/quick-review",
      gateway: "customer",
      lambda: "customer",
      controller: "items",
      action: "quick_review",
      auth: "cognito",
      tables: [:inventory, :containers, :item_changes, :item_listings]
    },
    {
      verb: "GET",
      path: "/items/recent",
      gateway: "customer",
      lambda: "customer",
      controller: "items",
      action: "recent",
      auth: "cognito",
      tables: [:inventory, :containers, :item_changes, :item_listings]
    },
    {
      verb: "GET",
      path: "/items/search",
      gateway: "customer",
      lambda: "customer",
      controller: "items",
      action: "search",
      auth: "cognito",
      tables: [:inventory, :containers, :item_changes, :item_listings]
    },
    {
      verb: "GET",
      path: "/account_balance",
      gateway: "customer",
      lambda: "customer",
      controller: "account_balance",
      action: "show",
      auth: "cognito",
      tables: [:customers]
    },
    {
      verb: "GET",
      path: "/account_members",
      gateway: "customer",
      lambda: "customer",
      controller: "account_members",
      action: "index",
      auth: "cognito",
      tables: [:account_members, :customers]
    },
    {
      verb: "POST",
      path: "/account_members",
      gateway: "customer",
      lambda: "customer",
      controller: "account_members",
      action: "create",
      auth: "cognito",
      tables: [:account_members, :customers]
    },
    {
      verb: "GET",
      path: "/available_slots",
      gateway: "customer",
      lambda: "customer",
      controller: "available_slots",
      action: "index",
      auth: "none",
      tables: [:availability_slots, :pickups]
    },
    {
      verb: "GET",
      path: "/bundles",
      gateway: "customer",
      lambda: "customer",
      controller: "bundles",
      action: "index",
      auth: "cognito",
      tables: [:inventory]
    },
    {
      verb: "POST",
      path: "/bundles",
      gateway: "customer",
      lambda: "customer",
      controller: "bundles",
      action: "create",
      auth: "cognito",
      tables: [:inventory]
    },
    {
      verb: "GET",
      path: "/connect_account",
      gateway: "customer",
      lambda: "customer",
      controller: "connect_account",
      action: "show",
      auth: "cognito",
      tables: [:customers]
    },
    {
      verb: "POST",
      path: "/connect_account",
      gateway: "customer",
      lambda: "customer",
      controller: "connect_account",
      action: "create",
      auth: "cognito",
      tables: [:customers]
    },
    {
      verb: "GET",
      path: "/containers",
      gateway: "customer",
      lambda: "customer",
      controller: "containers",
      action: "index",
      auth: "cognito",
      tables: [:containers, :inventory]
    },
    {
      verb: "GET",
      path: "/items",
      gateway: "customer",
      lambda: "customer",
      controller: "items",
      action: "index",
      auth: "cognito",
      tables: [:inventory, :containers, :item_changes, :item_listings]
    },
    {
      verb: "GET",
      path: "/pickups",
      gateway: "customer",
      lambda: "customer",
      controller: "pickups",
      action: "index",
      auth: "cognito",
      tables: [:pickups]
    },
    {
      verb: "POST",
      path: "/pickups",
      gateway: "customer",
      lambda: "customer",
      controller: "pickups",
      action: "create",
      auth: "cognito",
      tables: [:pickups]
    },
    {
      verb: "GET",
      path: "/profile",
      gateway: "customer",
      lambda: "customer",
      controller: "profile",
      action: "show",
      auth: "cognito",
      tables: [:customers]
    },
    {
      verb: "PUT",
      path: "/profile",
      gateway: "customer",
      lambda: "customer",
      controller: "profile",
      action: "update",
      auth: "cognito",
      tables: [:customers]
    },
    {
      verb: "GET",
      path: "/returns",
      gateway: "customer",
      lambda: "customer",
      controller: "returns",
      action: "index",
      auth: "cognito",
      tables: [:returns, :inventory, :customers]
    },
    {
      verb: "POST",
      path: "/returns",
      gateway: "customer",
      lambda: "customer",
      controller: "returns",
      action: "create",
      auth: "cognito",
      tables: [:returns, :inventory, :customers]
    },
    {
      verb: "GET",
      path: "/suggestions",
      gateway: "customer",
      lambda: "customer",
      controller: "item_changes",
      action: "index",
      auth: "cognito",
      tables: [:item_changes, :inventory]
    },
    {
      verb: "GET",
      path: "/unsubscribe",
      gateway: "customer",
      lambda: "customer",
      controller: "operations",
      action: "unsubscribe",
      auth: "none",
      tables: [:customers, :email_suppressions]
    },
    {
      verb: "POST",
      path: "/account_members/{account_member_id}/accept",
      gateway: "customer",
      lambda: "customer",
      controller: "account_members",
      action: "accept",
      auth: "cognito",
      tables: [:account_members, :customers]
    },
    {
      verb: "POST",
      path: "/bundles/{bundle_id}/list-for-sale",
      gateway: "customer",
      lambda: "customer",
      controller: "bundles",
      action: "list_for_sale",
      auth: "cognito",
      tables: [:inventory]
    },
    {
      verb: "GET",
      path: "/containers/{container_id}/contents",
      gateway: "customer",
      lambda: "customer",
      controller: "containers",
      action: "contents",
      auth: "cognito",
      tables: [:containers, :inventory]
    },
    {
      verb: "GET",
      path: "/containers/{container_id}/path",
      gateway: "customer",
      lambda: "customer",
      controller: "containers",
      action: "path",
      auth: "cognito",
      tables: [:containers, :inventory]
    },
    {
      verb: "GET",
      path: "/containers/{container_id}/qr-code",
      gateway: "customer",
      lambda: "customer",
      controller: "containers",
      action: "qr_code",
      auth: "cognito",
      tables: [:containers, :inventory]
    },
    {
      verb: "POST",
      path: "/items/{item_id}/abandon",
      gateway: "customer",
      lambda: "customer",
      controller: "items",
      action: "abandon",
      auth: "cognito",
      tables: [:inventory, :containers, :item_changes, :item_listings]
    },
    {
      verb: "POST",
      path: "/items/{item_id}/approve-listing",
      gateway: "customer",
      lambda: "customer",
      controller: "items",
      action: "approve_listing",
      auth: "cognito",
      tables: [:inventory, :containers, :item_changes, :item_listings]
    },
    {
      verb: "POST",
      path: "/items/{item_id}/cancel-listing",
      gateway: "customer",
      lambda: "customer",
      controller: "items",
      action: "cancel_listing",
      auth: "cognito",
      tables: [:inventory, :containers, :item_changes, :item_listings]
    },
    {
      verb: "DELETE",
      path: "/items/{item_id}/images",
      gateway: "customer",
      lambda: "customer",
      controller: "items",
      action: "images",
      auth: "cognito",
      tables: [:inventory, :containers, :item_changes, :item_listings]
    },
    {
      verb: "POST",
      path: "/items/{item_id}/link-complement",
      gateway: "customer",
      lambda: "customer",
      controller: "items",
      action: "link_complement",
      auth: "cognito",
      tables: [:inventory, :containers, :item_changes, :item_listings]
    },
    {
      verb: "DELETE",
      path: "/items/{item_id}/link-complement",
      gateway: "customer",
      lambda: "customer",
      controller: "items",
      action: "unlink_complement",
      auth: "cognito",
      tables: [:inventory, :containers, :item_changes, :item_listings]
    },
    {
      verb: "POST",
      path: "/items/{item_id}/list-for-sale",
      gateway: "customer",
      lambda: "customer",
      controller: "items",
      action: "list_for_sale",
      auth: "cognito",
      tables: [:inventory, :containers, :item_changes, :item_listings]
    },
    {
      verb: "GET",
      path: "/items/{item_id}/listings",
      gateway: "customer",
      lambda: "customer",
      controller: "items",
      action: "listings",
      auth: "cognito",
      tables: [:inventory, :containers, :item_changes, :item_listings]
    },
    {
      verb: "GET",
      path: "/items/{item_id}/path",
      gateway: "customer",
      lambda: "customer",
      controller: "items",
      action: "path",
      auth: "cognito",
      tables: [:inventory, :containers, :item_changes, :item_listings]
    },
    {
      verb: "POST",
      path: "/items/{item_id}/reject-listing",
      gateway: "customer",
      lambda: "customer",
      controller: "items",
      action: "reject_listing",
      auth: "cognito",
      tables: [:inventory, :containers, :item_changes, :item_listings]
    },
    {
      verb: "POST",
      path: "/items/{item_id}/reorder-images",
      gateway: "customer",
      lambda: "customer",
      controller: "items",
      action: "reorder_images",
      auth: "cognito",
      tables: [:inventory, :containers, :item_changes, :item_listings]
    },
    {
      verb: "POST",
      path: "/items/{item_id}/suggestions",
      gateway: "customer",
      lambda: "customer",
      controller: "item_changes",
      action: "create",
      auth: "cognito",
      tables: [:inventory, :containers, :item_changes, :item_listings]
    },
    {
      verb: "PUT",
      path: "/items/{item_id}/update-minimum-price",
      gateway: "customer",
      lambda: "customer",
      controller: "items",
      action: "update_minimum_price",
      auth: "cognito",
      tables: [:inventory, :containers, :item_changes, :item_listings]
    },
    {
      verb: "POST",
      path: "/items/{item_id}/upload-image",
      gateway: "customer",
      lambda: "customer",
      controller: "items",
      action: "upload_image",
      auth: "cognito",
      tables: [:inventory, :containers, :item_changes, :item_listings]
    },
    {
      verb: "GET",
      path: "/pickups/{pickup_id}/items",
      gateway: "customer",
      lambda: "customer",
      controller: "pickups/items",
      action: "index",
      auth: "cognito",
      tables: [:pickups]
    },
    {
      verb: "POST",
      path: "/returns/{return_id}/items",
      gateway: "customer",
      lambda: "customer",
      controller: "returns",
      action: "add_items",
      auth: "cognito",
      tables: [:returns, :inventory, :customers]
    },
    {
      verb: "GET",
      path: "/account_members/{account_member_id}",
      gateway: "customer",
      lambda: "customer",
      controller: "account_members",
      action: "show",
      auth: "cognito",
      tables: [:account_members, :customers]
    },
    {
      verb: "PUT",
      path: "/account_members/{account_member_id}",
      gateway: "customer",
      lambda: "customer",
      controller: "account_members",
      action: "update",
      auth: "cognito",
      tables: [:account_members, :customers]
    },
    {
      verb: "DELETE",
      path: "/account_members/{account_member_id}",
      gateway: "customer",
      lambda: "customer",
      controller: "account_members",
      action: "destroy",
      auth: "cognito",
      tables: [:account_members, :customers]
    },
    {
      verb: "GET",
      path: "/bundles/{bundle_id}",
      gateway: "customer",
      lambda: "customer",
      controller: "bundles",
      action: "show",
      auth: "cognito",
      tables: [:inventory]
    },
    {
      verb: "PUT",
      path: "/bundles/{bundle_id}",
      gateway: "customer",
      lambda: "customer",
      controller: "bundles",
      action: "update",
      auth: "cognito",
      tables: [:inventory]
    },
    {
      verb: "DELETE",
      path: "/bundles/{bundle_id}",
      gateway: "customer",
      lambda: "customer",
      controller: "bundles",
      action: "destroy",
      auth: "cognito",
      tables: [:inventory]
    },
    {
      verb: "GET",
      path: "/containers/{container_id}",
      gateway: "customer",
      lambda: "customer",
      controller: "containers",
      action: "show",
      auth: "cognito",
      tables: [:containers, :inventory]
    },
    {
      verb: "GET",
      path: "/items/{item_id}",
      gateway: "customer",
      lambda: "customer",
      controller: "items",
      action: "show",
      auth: "cognito",
      tables: [:inventory, :containers, :item_changes, :item_listings]
    },
    {
      verb: "PUT",
      path: "/items/{item_id}",
      gateway: "customer",
      lambda: "customer",
      controller: "items",
      action: "update",
      auth: "cognito",
      tables: [:inventory, :containers, :item_changes, :item_listings]
    },
    {
      verb: "GET",
      path: "/items/{item_id}hello",
      gateway: "customer",
      lambda: "customer",
      controller: "items",
      action: "show",
      auth: "cognito",
      tables: [:inventory, :containers, :item_changes, :item_listings]
    },
    {
      verb: "GET",
      path: "/pickups/{pickup_id}",
      gateway: "customer",
      lambda: "customer",
      controller: "pickups",
      action: "show",
      auth: "cognito",
      tables: [:pickups]
    },
    {
      verb: "PUT",
      path: "/pickups/{pickup_id}",
      gateway: "customer",
      lambda: "customer",
      controller: "pickups",
      action: "update",
      auth: "cognito",
      tables: [:pickups]
    },
    {
      verb: "DELETE",
      path: "/pickups/{pickup_id}",
      gateway: "customer",
      lambda: "customer",
      controller: "pickups",
      action: "destroy",
      auth: "cognito",
      tables: [:pickups]
    },
    {
      verb: "GET",
      path: "/returns/{return_id}",
      gateway: "customer",
      lambda: "customer",
      controller: "returns",
      action: "show",
      auth: "cognito",
      tables: [:returns, :inventory, :customers]
    },
    {
      verb: "PUT",
      path: "/returns/{return_id}",
      gateway: "customer",
      lambda: "customer",
      controller: "returns",
      action: "update",
      auth: "cognito",
      tables: [:returns, :inventory, :customers]
    },
    {
      verb: "DELETE",
      path: "/returns/{return_id}",
      gateway: "customer",
      lambda: "customer",
      controller: "returns",
      action: "destroy",
      auth: "cognito",
      tables: [:returns, :inventory, :customers]
    },
    {
      verb: "GET",
      path: "/suggestions/{suggestion_id}",
      gateway: "customer",
      lambda: "customer",
      controller: "item_changes",
      action: "show",
      auth: "cognito",
      tables: [:item_changes, :inventory]
    },
    {
      verb: "PUT",
      path: "/suggestions/{suggestion_id}",
      gateway: "customer",
      lambda: "customer",
      controller: "item_changes",
      action: "update",
      auth: "cognito",
      tables: [:item_changes, :inventory]
    },
    {
      verb: "DELETE",
      path: "/suggestions/{suggestion_id}",
      gateway: "customer",
      lambda: "customer",
      controller: "item_changes",
      action: "destroy",
      auth: "cognito",
      tables: [:item_changes, :inventory]
    },
    {
      verb: "DELETE",
      path: "/returns/{return_id}/items/{item_id}",
      gateway: "customer",
      lambda: "customer",
      controller: "returns",
      action: "remove_item",
      auth: "cognito",
      tables: [:returns, :inventory, :customers]
    }
  ].freeze
end
