# frozen_string_literal: true

# Auto-generated by: ruby scripts/list_routes.rb --ruby-output landing
# Do not edit manually - regenerate with `scripts/list_routes.rb --ruby-output landing'

module Routes
  LANDING = [
    {
      verb: "POST",
      path: "/contact",
      gateway: "onboarding",
      lambda: "landing",
      controller: "landing",
      action: "contact",
      auth: "none",
      tables: []
    },
    {
      verb: "POST",
      path: "/waitlist",
      gateway: "onboarding",
      lambda: "landing",
      controller: "landing",
      action: "waitlist",
      auth: "none",
      tables: [:waitlisters]
    },
    {
      verb: "POST",
      path: "/zip_code_interests",
      gateway: "onboarding",
      lambda: "landing",
      controller: "landing",
      action: "zip_code_interests",
      auth: "none",
      tables: ["zip_code_interests"]
    }
  ].freeze
end
