# frozen_string_literal: true

# Auto-generated by: ruby scripts/list_routes.rb --ruby-output onboarding
# Do not edit manually - regenerate with `scripts/list_routes.rb --ruby-output onboarding'

module Routes
  ONBOARDING = [
    {
      verb: "GET",
      path: "/check-account",
      gateway: "onboarding",
      lambda: "onboarding",
      controller: "onboarding",
      action: "check_account",
      auth: "none",
      tables: [:customers]
    },
    {
      verb: "POST",
      path: "/ensure-customer",
      gateway: "onboarding",
      lambda: "onboarding",
      controller: "onboarding",
      action: "ensure_customer",
      auth: "cognito",
      tables: [:customers, :containers]
    },
    {
      verb: "GET",
      path: "/has-pickups",
      gateway: "onboarding",
      lambda: "onboarding",
      controller: "onboarding",
      action: "has_pickups",
      auth: "none",
      tables: [:pickups, :customers]
    },
    {
      verb: "POST",
      path: "/payment-method",
      gateway: "onboarding",
      lambda: "onboarding",
      controller: "onboarding",
      action: "payment_method",
      auth: "none",
      tables: []
    },
    {
      verb: "POST",
      path: "/resend-verification",
      gateway: "onboarding",
      lambda: "onboarding",
      controller: "onboarding",
      action: "resend_verification",
      auth: "none",
      tables: []
    },
    {
      verb: "POST",
      path: "/schedule",
      gateway: "onboarding",
      lambda: "onboarding",
      controller: "onboarding",
      action: "schedule",
      auth: "none",
      tables: [:pickups, :customers, :availability_slots]
    },
    {
      verb: "POST",
      path: "/signup",
      gateway: "onboarding",
      lambda: "onboarding",
      controller: "onboarding",
      action: "signup",
      auth: "none",
      tables: [:customers, :click_wrap_acceptances, :containers]
    },
    {
      verb: "GET",
      path: "/invitations/{invitation_id}",
      gateway: "onboarding",
      lambda: "onboarding",
      controller: "invitations",
      action: "show",
      auth: "none",
      tables: [:account_members, :customers]
    }
  ].freeze
end
