# frozen_string_literal: true

# Auto-generated by: ruby scripts/list_routes.rb --ruby-output ops
# Do not edit manually - regenerate with `scripts/list_routes.rb --ruby-output ops'

module Routes
  OPS = [
    {
      verb: "PUT",
      path: "/employees/me/service-zip-codes",
      gateway: "ops",
      lambda: "ops",
      controller: "employees",
      action: "service_zip_codes",
      auth: "cognito",
      tables: [:employees]
    },
    {
      verb: "GET",
      path: "/item_changes/pending/count",
      gateway: "ops",
      lambda: "ops",
      controller: "item_changes",
      action: :pending_count,
      auth: "cognito",
      tables: [:item_changes, :inventory]
    },
    {
      verb: "POST",
      path: "/availability_slots/block_dates",
      gateway: "ops",
      lambda: "ops",
      controller: "availability_slots",
      action: "block_dates",
      auth: "cognito",
      tables: [:availability_slots, :employees, :pickups]
    },
    {
      verb: "POST",
      path: "/availability_slots/bulk",
      gateway: "ops",
      lambda: "ops",
      controller: "availability_slots",
      action: "bulk",
      auth: "cognito",
      tables: [:availability_slots, :employees, :pickups]
    },
    {
      verb: "GET",
      path: "/billing/customers",
      gateway: "ops",
      lambda: "ops",
      controller: "billing",
      action: "customers",
      auth: "cognito",
      tables: [:inventory, :customers, :billing_records]
    },
    {
      verb: "GET",
      path: "/billing/overview",
      gateway: "ops",
      lambda: "ops",
      controller: "billing",
      action: "overview",
      auth: "cognito",
      tables: [:inventory, :customers, :billing_records]
    },
    {
      verb: "GET",
      path: "/billing/rate",
      gateway: "ops",
      lambda: "ops",
      controller: "billing",
      action: "rate",
      auth: "cognito",
      tables: []
    },
    {
      verb: "POST",
      path: "/cart/add",
      gateway: "ops",
      lambda: "ops",
      controller: "cart",
      action: "add",
      auth: "cognito",
      tables: ["cart"]
    },
    {
      verb: "POST",
      path: "/containers/bulk",
      gateway: "ops",
      lambda: "ops",
      controller: "containers",
      action: "bulk_create",
      auth: "cognito",
      tables: [:containers, :inventory, :billing_events]
    },
    {
      verb: "GET",
      path: "/containers/consolidation-suggestions",
      gateway: "ops",
      lambda: "ops",
      controller: "containers",
      action: "consolidation_suggestions",
      auth: "cognito",
      tables: [:containers]
    },
    {
      verb: "GET",
      path: "/containers/search",
      gateway: "ops",
      lambda: "ops",
      controller: "containers",
      action: "search",
      auth: "cognito",
      tables: [:containers, :inventory, :billing_events]
    },
    {
      verb: "POST",
      path: "/containers/shippable",
      gateway: "ops",
      lambda: "ops",
      controller: "containers",
      action: "create_shippable",
      auth: "cognito",
      tables: [:containers, :inventory, :billing_events, :movements]
    },
    {
      verb: "GET",
      path: "/containers/types",
      gateway: "ops",
      lambda: "ops",
      controller: "containers",
      action: "types",
      auth: "cognito",
      tables: [:containers, :inventory, :billing_events]
    },
    {
      verb: "GET",
      path: "/customers/search",
      gateway: "ops",
      lambda: "ops",
      controller: "customers",
      action: "search",
      auth: "cognito",
      tables: [:customers, :containers, :inventory, :availability_slots]
    },
    {
      verb: "GET",
      path: "/dashboard/alerts",
      gateway: "ops",
      lambda: "ops",
      controller: "dashboard",
      action: "alerts",
      auth: "cognito",
      tables: [:employees, :pickups, :inventory, :customers, :containers]
    },
    {
      verb: "GET",
      path: "/dashboard/schedule",
      gateway: "ops",
      lambda: "ops",
      controller: "dashboard",
      action: "schedule",
      auth: "cognito",
      tables: [:employees, :pickups, :returns, :customers]
    },
    {
      verb: "GET",
      path: "/employees/me",
      gateway: "ops",
      lambda: "ops",
      controller: "employees",
      action: "me",
      auth: "cognito",
      tables: [:employees]
    },
    {
      verb: "PUT",
      path: "/employees/me",
      gateway: "ops",
      lambda: "ops",
      controller: "employees",
      action: "update_me",
      auth: "cognito",
      tables: [:employees]
    },
    {
      verb: "GET",
      path: "/item_changes/pending",
      gateway: "ops",
      lambda: "ops",
      controller: "item_changes",
      action: "pending",
      auth: "cognito",
      tables: [:item_changes, :inventory]
    },
    {
      verb: "GET",
      path: "/items/ai-models",
      gateway: "ops",
      lambda: "ops",
      controller: "items",
      action: "ai_models",
      auth: "cognito",
      tables: [:inventory, :serp_pricing_results]
    },
    {
      verb: "POST",
      path: "/items/bulk-request-approval",
      gateway: "ops",
      lambda: "ops",
      controller: "items",
      action: "bulk_request_approval",
      auth: "cognito",
      tables: [:inventory, :serp_pricing_results]
    },
    {
      verb: "PUT",
      path: "/items/bulk-update",
      gateway: "ops",
      lambda: "ops",
      controller: "items",
      action: "bulk_update",
      auth: "cognito",
      tables: [:inventory, :serp_pricing_results]
    },
    {
      verb: "GET",
      path: "/items/for-sale",
      gateway: "ops",
      lambda: "ops",
      controller: "items",
      action: "for_sale",
      auth: "cognito",
      tables: [:inventory, :serp_pricing_results]
    },
    {
      verb: "POST",
      path: "/items/merge",
      gateway: "ops",
      lambda: "ops",
      controller: "items",
      action: "merge",
      auth: "cognito",
      tables: [:inventory, :serp_pricing_results]
    },
    {
      verb: "GET",
      path: "/items/missing-complements",
      gateway: "ops",
      lambda: "ops",
      controller: "items",
      action: "missing_complements",
      auth: "cognito",
      tables: [:inventory, :serp_pricing_results]
    },
    {
      verb: "GET",
      path: "/items/quick-review",
      gateway: "ops",
      lambda: "ops",
      controller: "items",
      action: "quick_review",
      auth: "cognito",
      tables: [:inventory, :serp_pricing_results]
    },
    {
      verb: "GET",
      path: "/items/search",
      gateway: "ops",
      lambda: "ops",
      controller: "items",
      action: "search",
      auth: "cognito",
      tables: [:inventory, :serp_pricing_results, :containers]
    },
    {
      verb: "GET",
      path: "/items/size-pricing",
      gateway: "ops",
      lambda: "ops",
      controller: "items",
      action: "size_pricing",
      auth: "cognito",
      tables: [:inventory, :serp_pricing_results]
    },
    {
      verb: "POST",
      path: "/movement-queue/process",
      gateway: "ops",
      lambda: "ops",
      controller: "movement_queue",
      action: "process",
      auth: "cognito",
      tables: [:movement_queue, :inventory, :containers, :movements, :billing_events]
    },
    {
      verb: "GET",
      path: "/movement-queue/status",
      gateway: "ops",
      lambda: "ops",
      controller: "movement_queue",
      action: "status",
      auth: "cognito",
      tables: [:movement_queue]
    },
    {
      verb: "GET",
      path: "/movements/history",
      gateway: "ops",
      lambda: "ops",
      controller: "movements",
      action: "history",
      auth: "cognito",
      tables: [:movements, :containers, :inventory]
    },
    {
      verb: "POST",
      path: "/operations/undo",
      gateway: "ops",
      lambda: "ops",
      controller: "operations",
      action: "undo",
      auth: "cognito",
      tables: [:inventory, :containers, :billing_events]
    },
    {
      verb: "GET",
      path: "/statuses/pickups",
      gateway: "ops",
      lambda: "ops",
      controller: "statuses",
      action: "pickups",
      auth: "cognito",
      tables: [:pickups]
    },
    {
      verb: "GET",
      path: "/statuses/returns",
      gateway: "ops",
      lambda: "ops",
      controller: "statuses",
      action: "returns",
      auth: "cognito",
      tables: [:returns]
    },
    {
      verb: "GET",
      path: "/action_logs",
      gateway: "ops",
      lambda: "ops",
      controller: "action_logs",
      action: "index",
      auth: "cognito",
      tables: [:action_logs]
    },
    {
      verb: "GET",
      path: "/android_builds",
      gateway: "ops",
      lambda: "ops",
      controller: "android_builds",
      action: "index",
      auth: "cognito",
      tables: []
    },
    {
      verb: "GET",
      path: "/availability_slots",
      gateway: "ops",
      lambda: "ops",
      controller: "availability_slots",
      action: "index",
      auth: "cognito",
      tables: [:availability_slots, :employees, :pickups]
    },
    {
      verb: "POST",
      path: "/availability_slots",
      gateway: "ops",
      lambda: "ops",
      controller: "availability_slots",
      action: "create",
      auth: "cognito",
      tables: [:availability_slots, :employees, :pickups]
    },
    {
      verb: "GET",
      path: "/bundles",
      gateway: "ops",
      lambda: "ops",
      controller: "bundles",
      action: "index",
      auth: "cognito",
      tables: [:inventory]
    },
    {
      verb: "POST",
      path: "/bundles",
      gateway: "ops",
      lambda: "ops",
      controller: "bundles",
      action: "create",
      auth: "cognito",
      tables: [:inventory]
    },
    {
      verb: "GET",
      path: "/cart",
      gateway: "ops",
      lambda: "ops",
      controller: "ops",
      action: "cart",
      auth: "cognito",
      tables: ["cart"]
    },
    {
      verb: "GET",
      path: "/containers",
      gateway: "ops",
      lambda: "ops",
      controller: "containers",
      action: "index",
      auth: "cognito",
      tables: [:containers, :inventory, :billing_events]
    },
    {
      verb: "POST",
      path: "/containers",
      gateway: "ops",
      lambda: "ops",
      controller: "containers",
      action: "create",
      auth: "cognito",
      tables: [:containers, :inventory, :billing_events]
    },
    {
      verb: "GET",
      path: "/customers",
      gateway: "ops",
      lambda: "ops",
      controller: "customers",
      action: "index",
      auth: "cognito",
      tables: [:customers, :containers, :inventory, :availability_slots]
    },
    {
      verb: "POST",
      path: "/customers",
      gateway: "ops",
      lambda: "ops",
      controller: "customers",
      action: "create",
      auth: "cognito",
      tables: [:customers, :containers, :inventory, :availability_slots]
    },
    {
      verb: "GET",
      path: "/employees",
      gateway: "ops",
      lambda: "ops",
      controller: "employees",
      action: "index",
      auth: "cognito",
      tables: [:employees]
    },
    {
      verb: "POST",
      path: "/employees",
      gateway: "ops",
      lambda: "ops",
      controller: "employees",
      action: "create",
      auth: "cognito",
      tables: [:employees]
    },
    {
      verb: "GET",
      path: "/inventory",
      gateway: "ops",
      lambda: "ops",
      controller: "inventory",
      action: "index",
      auth: "cognito",
      tables: [:inventory]
    },
    {
      verb: "GET",
      path: "/item_changes",
      gateway: "ops",
      lambda: "ops",
      controller: "item_changes",
      action: "index",
      auth: "cognito",
      tables: [:item_changes, :inventory]
    },
    {
      verb: "POST",
      path: "/item_changes",
      gateway: "ops",
      lambda: "ops",
      controller: "item_changes",
      action: "create",
      auth: "cognito",
      tables: [:item_changes, :inventory]
    },
    {
      verb: "GET",
      path: "/items",
      gateway: "ops",
      lambda: "ops",
      controller: "items",
      action: "index",
      auth: "cognito",
      tables: [:inventory, :serp_pricing_results]
    },
    {
      verb: "POST",
      path: "/items",
      gateway: "ops",
      lambda: "ops",
      controller: "items",
      action: "create",
      auth: "cognito",
      tables: [:inventory, :serp_pricing_results]
    },
    {
      verb: "GET",
      path: "/pickups",
      gateway: "ops",
      lambda: "ops",
      controller: "pickups",
      action: "index",
      auth: "cognito",
      tables: [:pickups, :customers]
    },
    {
      verb: "POST",
      path: "/pickups",
      gateway: "ops",
      lambda: "ops",
      controller: "pickups",
      action: "create",
      auth: "cognito",
      tables: [:pickups, :customers]
    },
    {
      verb: "GET",
      path: "/returns",
      gateway: "ops",
      lambda: "ops",
      controller: "returns",
      action: "index",
      auth: "cognito",
      tables: [:returns, :inventory, :customers]
    },
    {
      verb: "GET",
      path: "/terms_acceptances",
      gateway: "ops",
      lambda: "ops",
      controller: "terms_acceptances",
      action: "index",
      auth: "cognito",
      tables: [:terms_acceptances]
    },
    {
      verb: "GET",
      path: "/waitlist",
      gateway: "ops",
      lambda: "ops",
      controller: "waitlist",
      action: "index",
      auth: "cognito",
      tables: [:waitlisters]
    },
    {
      verb: "POST",
      path: "/containers/{container_id}/qr-code/print",
      gateway: "ops",
      lambda: "ops",
      controller: "containers",
      action: "print_qr_code",
      auth: "cognito",
      tables: [:containers, :inventory, :billing_events]
    },
    {
      verb: "POST",
      path: "/account_balance/{customer_id}/credit",
      gateway: "ops",
      lambda: "ops",
      controller: "account_balance",
      action: "credit",
      auth: "cognito",
      tables: [:customers]
    },
    {
      verb: "POST",
      path: "/account_balance/{customer_id}/debit",
      gateway: "ops",
      lambda: "ops",
      controller: "account_balance",
      action: "debit",
      auth: "cognito",
      tables: [:customers]
    },
    {
      verb: "PUT",
      path: "/availability_slots/recurring/{recurring_group_id}",
      gateway: "ops",
      lambda: "ops",
      controller: "availability_slots",
      action: "recurring",
      auth: "cognito",
      tables: [:availability_slots, :employees, :pickups]
    },
    {
      verb: "DELETE",
      path: "/availability_slots/recurring/{recurring_group_id}",
      gateway: "ops",
      lambda: "ops",
      controller: "availability_slots",
      action: "recurring",
      auth: "cognito",
      tables: [:availability_slots, :employees, :pickups]
    },
    {
      verb: "DELETE",
      path: "/availability_slots/{availability_slot_id}/with_reassignment",
      gateway: "ops",
      lambda: "ops",
      controller: "availability_slots",
      action: "with_reassignment",
      auth: "cognito",
      tables: [:availability_slots, :employees, :pickups]
    },
    {
      verb: "GET",
      path: "/billing/customer/{customer_id}",
      gateway: "ops",
      lambda: "ops",
      controller: "billing",
      action: "customer",
      auth: "cognito",
      tables: [:inventory, :customers, :billing_records]
    },
    {
      verb: "POST",
      path: "/bundles/{bundle_id}/add-items",
      gateway: "ops",
      lambda: "ops",
      controller: "bundles",
      action: "add_items",
      auth: "cognito",
      tables: [:inventory]
    },
    {
      verb: "POST",
      path: "/bundles/{bundle_id}/remove-items",
      gateway: "ops",
      lambda: "ops",
      controller: "bundles",
      action: "remove_items",
      auth: "cognito",
      tables: [:inventory]
    },
    {
      verb: "GET",
      path: "/connect_account/{customer_id}/payout-status",
      gateway: "ops",
      lambda: "ops",
      controller: "connect_account",
      action: "payout_status",
      auth: "cognito",
      tables: [:customers, :action_logs]
    },
    {
      verb: "POST",
      path: "/connect_account/{customer_id}/process-external-sale-payout",
      gateway: "ops",
      lambda: "ops",
      controller: "connect_account",
      action: "process_external_sale_payout",
      auth: "cognito",
      tables: [:customers, :action_logs, :inventory_items]
    },
    {
      verb: "POST",
      path: "/connect_account/{customer_id}/sync",
      gateway: "ops",
      lambda: "ops",
      controller: "connect_account",
      action: "sync",
      auth: "cognito",
      tables: [:customers]
    },
    {
      verb: "POST",
      path: "/connect_account/{customer_id}/transfer",
      gateway: "ops",
      lambda: "ops",
      controller: "connect_account",
      action: "transfer",
      auth: "cognito",
      tables: [:customers, :action_logs]
    },
    {
      verb: "POST",
      path: "/containers/{container_id}/add-items",
      gateway: "ops",
      lambda: "ops",
      controller: "containers",
      action: "add_items",
      auth: "cognito",
      tables: [:containers, :inventory, :billing_events, :movements]
    },
    {
      verb: "PUT",
      path: "/containers/{container_id}/assign",
      gateway: "ops",
      lambda: "ops",
      controller: "containers",
      action: "assign",
      auth: "cognito",
      tables: [:containers, :inventory, :billing_events]
    },
    {
      verb: "POST",
      path: "/containers/{container_id}/bulk-move",
      gateway: "ops",
      lambda: "ops",
      controller: "containers",
      action: "bulk_move",
      auth: "cognito",
      tables: [:containers, :inventory, :billing_events, :movements]
    },
    {
      verb: "GET",
      path: "/containers/{container_id}/children",
      gateway: "ops",
      lambda: "ops",
      controller: "containers",
      action: "children",
      auth: "cognito",
      tables: [:containers, :inventory, :billing_events]
    },
    {
      verb: "GET",
      path: "/containers/{container_id}/contents",
      gateway: "ops",
      lambda: "ops",
      controller: "containers",
      action: "contents",
      auth: "cognito",
      tables: [:containers, :inventory, :billing_events]
    },
    {
      verb: "POST",
      path: "/containers/{container_id}/duplicate",
      gateway: "ops",
      lambda: "ops",
      controller: "containers",
      action: "duplicate",
      auth: "cognito",
      tables: [:containers, :inventory, :billing_events]
    },
    {
      verb: "GET",
      path: "/containers/{container_id}/items",
      gateway: "ops",
      lambda: "ops",
      controller: "containers",
      action: "items",
      auth: "cognito",
      tables: [:containers, :inventory, :billing_events]
    },
    {
      verb: "POST",
      path: "/containers/{container_id}/move",
      gateway: "ops",
      lambda: "ops",
      controller: "containers",
      action: "move",
      auth: "cognito",
      tables: [:containers, :inventory, :billing_events, :movements]
    },
    {
      verb: "PUT",
      path: "/containers/{container_id}/move",
      gateway: "ops",
      lambda: "ops",
      controller: "containers",
      action: "move",
      auth: "cognito",
      tables: [:containers, :inventory, :billing_events, :movements]
    },
    {
      verb: "GET",
      path: "/containers/{container_id}/path",
      gateway: "ops",
      lambda: "ops",
      controller: "containers",
      action: "path",
      auth: "cognito",
      tables: [:containers, :inventory, :billing_events]
    },
    {
      verb: "GET",
      path: "/containers/{container_id}/qr-code",
      gateway: "ops",
      lambda: "ops",
      controller: "containers",
      action: "qr_code",
      auth: "cognito",
      tables: [:containers, :inventory, :billing_events]
    },
    {
      verb: "PUT",
      path: "/containers/{container_id}/unassign",
      gateway: "ops",
      lambda: "ops",
      controller: "containers",
      action: "unassign",
      auth: "cognito",
      tables: [:containers, :inventory, :billing_events]
    },
    {
      verb: "GET",
      path: "/customers/{customer_id}/account_members",
      gateway: "ops",
      lambda: "ops",
      controller: "customers",
      action: "account_members",
      auth: "cognito",
      tables: [:customers, :containers, :inventory, :availability_slots, :account_members]
    },
    {
      verb: "GET",
      path: "/customers/{customer_id}/inventory",
      gateway: "ops",
      lambda: "ops",
      controller: "customers",
      action: "inventory",
      auth: "cognito",
      tables: [:customers, :containers, :inventory, :availability_slots]
    },
    {
      verb: "GET",
      path: "/customers/{customer_id}/items",
      gateway: "ops",
      lambda: "ops",
      controller: "customers/items",
      action: "index",
      auth: "cognito",
      tables: [:customers, :containers, :inventory, :availability_slots, :pickups]
    },
    {
      verb: "POST",
      path: "/customers/{customer_id}/items",
      gateway: "ops",
      lambda: "ops",
      controller: "customers/items",
      action: "create",
      auth: "cognito",
      tables: [:customers, :containers, :inventory, :availability_slots, :pickups]
    },
    {
      verb: "POST",
      path: "/customers/{customer_id}/request-item-info-notification",
      gateway: "ops",
      lambda: "ops",
      controller: "customers",
      action: "request_item_info_notification",
      auth: "cognito",
      tables: [:customers, :containers, :inventory, :availability_slots]
    },
    {
      verb: "POST",
      path: "/customers/{customer_id}/returns",
      gateway: "ops",
      lambda: "ops",
      controller: "customers/returns",
      action: "create",
      auth: "cognito",
      tables: [:customers, :containers, :inventory, :availability_slots, :returns]
    },
    {
      verb: "POST",
      path: "/item_changes/{item_change_id}/approve",
      gateway: "ops",
      lambda: "ops",
      controller: "item_changes",
      action: "approve",
      auth: "cognito",
      tables: [:item_changes, :inventory]
    },
    {
      verb: "POST",
      path: "/item_changes/{item_change_id}/partial-approve",
      gateway: "ops",
      lambda: "ops",
      controller: "item_changes",
      action: "partial_approve",
      auth: "cognito",
      tables: [:item_changes, :inventory]
    },
    {
      verb: "POST",
      path: "/item_changes/{item_change_id}/reject",
      gateway: "ops",
      lambda: "ops",
      controller: "item_changes",
      action: "reject",
      auth: "cognito",
      tables: [:item_changes, :inventory]
    },
    {
      verb: "POST",
      path: "/items/{item_id}/add-images",
      gateway: "ops",
      lambda: "ops",
      controller: "items",
      action: "add_images",
      auth: "cognito",
      tables: [:inventory, :serp_pricing_results]
    },
    {
      verb: "POST",
      path: "/items/{item_id}/analyze-with-ai",
      gateway: "ops",
      lambda: "ops",
      controller: "items",
      action: "analyze_with_ai",
      auth: "cognito",
      tables: [:inventory, :serp_pricing_results]
    },
    {
      verb: "POST",
      path: "/items/{item_id}/barcode-select",
      gateway: "ops",
      lambda: "ops",
      controller: "items",
      action: "barcode_select",
      auth: "cognito",
      tables: [:inventory, :serp_pricing_results]
    },
    {
      verb: "POST",
      path: "/items/{item_id}/cancel-customer-info",
      gateway: "ops",
      lambda: "ops",
      controller: "items",
      action: "cancel_customer_info",
      auth: "cognito",
      tables: [:inventory, :serp_pricing_results]
    },
    {
      verb: "GET",
      path: "/items/{item_id}/download-listing-photos",
      gateway: "ops",
      lambda: "ops",
      controller: "items",
      action: "download_listing_photos",
      auth: "cognito",
      tables: [:inventory, :serp_pricing_results]
    },
    {
      verb: "POST",
      path: "/items/{item_id}/generate-listing-description",
      gateway: "ops",
      lambda: "ops",
      controller: "items",
      action: "generate_listing_description",
      auth: "cognito",
      tables: [:inventory, :serp_pricing_results]
    },
    {
      verb: "DELETE",
      path: "/items/{item_id}/images",
      gateway: "ops",
      lambda: "ops",
      controller: "items",
      action: "images",
      auth: "cognito",
      tables: [:inventory, :serp_pricing_results]
    },
    {
      verb: "POST",
      path: "/items/{item_id}/link-complement",
      gateway: "ops",
      lambda: "ops",
      controller: "items",
      action: "link_complement",
      auth: "cognito",
      tables: [:inventory, :serp_pricing_results]
    },
    {
      verb: "DELETE",
      path: "/items/{item_id}/link-complement",
      gateway: "ops",
      lambda: "ops",
      controller: "items",
      action: "unlink_complement",
      auth: "cognito",
      tables: [:inventory, :serp_pricing_results]
    },
    {
      verb: "GET",
      path: "/items/{item_id}/listings",
      gateway: "ops",
      lambda: "ops",
      controller: "items",
      action: "item_listings_index",
      auth: "cognito",
      tables: [:inventory, :serp_pricing_results, :item_listings]
    },
    {
      verb: "POST",
      path: "/items/{item_id}/listings",
      gateway: "ops",
      lambda: "ops",
      controller: "items",
      action: "create_item_listing",
      auth: "cognito",
      tables: [:inventory, :serp_pricing_results, :item_listings, :sell_events]
    },
    {
      verb: "POST",
      path: "/items/{item_id}/lookup-barcode",
      gateway: "ops",
      lambda: "ops",
      controller: "items",
      action: "lookup_barcode",
      auth: "cognito",
      tables: [:inventory, :serp_pricing_results]
    },
    {
      verb: "POST",
      path: "/items/{item_id}/mark-returned",
      gateway: "ops",
      lambda: "ops",
      controller: "items",
      action: "mark_returned",
      auth: "cognito",
      tables: [:inventory, :serp_pricing_results]
    },
    {
      verb: "POST",
      path: "/items/{item_id}/mark-sold",
      gateway: "ops",
      lambda: "ops",
      controller: "items",
      action: "mark_sold",
      auth: "cognito",
      tables: [:inventory, :serp_pricing_results, :sell_events, :item_listings, :customers]
    },
    {
      verb: "POST",
      path: "/items/{item_id}/move",
      gateway: "ops",
      lambda: "ops",
      controller: "items",
      action: "move",
      auth: "cognito",
      tables: [:inventory, :serp_pricing_results, :containers, :movements, :billing_events]
    },
    {
      verb: "PUT",
      path: "/items/{item_id}/move",
      gateway: "ops",
      lambda: "ops",
      controller: "items",
      action: "move",
      auth: "cognito",
      tables: [:inventory, :serp_pricing_results, :containers, :movements, :billing_events]
    },
    {
      verb: "GET",
      path: "/items/{item_id}/path",
      gateway: "ops",
      lambda: "ops",
      controller: "items",
      action: "path",
      auth: "cognito",
      tables: [:inventory, :serp_pricing_results, :containers]
    },
    {
      verb: "PUT",
      path: "/items/{item_id}/payout-status",
      gateway: "ops",
      lambda: "ops",
      controller: "items",
      action: "payout_status",
      auth: "cognito",
      tables: [:inventory, :serp_pricing_results, :action_logs]
    },
    {
      verb: "POST",
      path: "/items/{item_id}/refresh-pricing",
      gateway: "ops",
      lambda: "ops",
      controller: "items",
      action: "refresh_pricing",
      auth: "cognito",
      tables: [:inventory, :serp_pricing_results]
    },
    {
      verb: "POST",
      path: "/items/{item_id}/reorder-images",
      gateway: "ops",
      lambda: "ops",
      controller: "items",
      action: "reorder_images",
      auth: "cognito",
      tables: [:inventory, :serp_pricing_results]
    },
    {
      verb: "POST",
      path: "/items/{item_id}/replace-image",
      gateway: "ops",
      lambda: "ops",
      controller: "items",
      action: "replace_image",
      auth: "cognito",
      tables: [:inventory, :serp_pricing_results]
    },
    {
      verb: "POST",
      path: "/items/{item_id}/request-customer-info",
      gateway: "ops",
      lambda: "ops",
      controller: "items",
      action: "request_customer_info",
      auth: "cognito",
      tables: [:inventory, :serp_pricing_results, :item_changes]
    },
    {
      verb: "GET",
      path: "/items/{item_id}/sell-history",
      gateway: "ops",
      lambda: "ops",
      controller: "items",
      action: "sell_history",
      auth: "cognito",
      tables: [:inventory, :serp_pricing_results, :sell_events, :item_listings]
    },
    {
      verb: "PUT",
      path: "/items/{item_id}/sell-status",
      gateway: "ops",
      lambda: "ops",
      controller: "items",
      action: "sell_status",
      auth: "cognito",
      tables: [:inventory, :serp_pricing_results, :sell_events, :item_listings, :customers]
    },
    {
      verb: "POST",
      path: "/items/{item_id}/set-image-listing-status",
      gateway: "ops",
      lambda: "ops",
      controller: "items",
      action: "set_image_listing_status",
      auth: "cognito",
      tables: [:inventory, :serp_pricing_results]
    },
    {
      verb: "POST",
      path: "/items/{item_id}/sync-payout",
      gateway: "ops",
      lambda: "ops",
      controller: "items",
      action: "sync_payout",
      auth: "cognito",
      tables: [:inventory, :serp_pricing_results, :action_logs]
    },
    {
      verb: "POST",
      path: "/items/{item_id}/upload-image",
      gateway: "ops",
      lambda: "ops",
      controller: "items",
      action: "upload_image",
      auth: "cognito",
      tables: [:inventory, :serp_pricing_results]
    },
    {
      verb: "POST",
      path: "/movement-queue/{id}/cancel",
      gateway: "ops",
      lambda: "ops",
      controller: "movement_queue",
      action: "cancel",
      auth: "cognito",
      tables: [:movement_queue]
    },
    {
      verb: "POST",
      path: "/pickups/{pickup_id}/assign",
      gateway: "ops",
      lambda: "ops",
      controller: "pickups",
      action: "assign",
      auth: "cognito",
      tables: [:pickups, :customers, :availability_slots, :employees]
    },
    {
      verb: "POST",
      path: "/pickups/{pickup_id}/claim",
      gateway: "ops",
      lambda: "ops",
      controller: "pickups",
      action: "claim",
      auth: "cognito",
      tables: [:pickups, :customers, :availability_slots, :employees]
    },
    {
      verb: "DELETE",
      path: "/pickups/{pickup_id}/unassign",
      gateway: "ops",
      lambda: "ops",
      controller: "pickups",
      action: "unassign",
      auth: "cognito",
      tables: [:pickups, :customers, :availability_slots]
    },
    {
      verb: "POST",
      path: "/returns/{return_id}/assign",
      gateway: "ops",
      lambda: "ops",
      controller: "returns",
      action: "assign",
      auth: "cognito",
      tables: [:returns, :inventory, :customers, :availability_slots, :employees]
    },
    {
      verb: "POST",
      path: "/returns/{return_id}/complete",
      gateway: "ops",
      lambda: "ops",
      controller: "returns",
      action: "complete",
      auth: "cognito",
      tables: [:returns, :inventory, :customers]
    },
    {
      verb: "POST",
      path: "/waitlist/{waitlist_id}/invite",
      gateway: "ops",
      lambda: "ops",
      controller: "waitlist",
      action: "invite",
      auth: "cognito",
      tables: [:waitlisters]
    },
    {
      verb: "POST",
      path: "/waitlist/{waitlist_id}/mark-joined",
      gateway: "ops",
      lambda: "ops",
      controller: "waitlist",
      action: "mark_joined",
      auth: "cognito",
      tables: [:waitlisters]
    },
    {
      verb: "POST",
      path: "/waitlist/{waitlist_id}/reset",
      gateway: "ops",
      lambda: "ops",
      controller: "waitlist",
      action: "reset",
      auth: "cognito",
      tables: [:waitlisters]
    },
    {
      verb: "GET",
      path: "/account_balance/{customer_id}",
      gateway: "ops",
      lambda: "ops",
      controller: "account_balance",
      action: "show",
      auth: "cognito",
      tables: [:customers]
    },
    {
      verb: "GET",
      path: "/action_logs/{action_log_id}",
      gateway: "ops",
      lambda: "ops",
      controller: "action_logs",
      action: "show",
      auth: "cognito",
      tables: [:action_logs]
    },
    {
      verb: "GET",
      path: "/availability_slots/{availability_slot_id}",
      gateway: "ops",
      lambda: "ops",
      controller: "availability_slots",
      action: "show",
      auth: "cognito",
      tables: [:availability_slots, :employees, :pickups]
    },
    {
      verb: "PUT",
      path: "/availability_slots/{availability_slot_id}",
      gateway: "ops",
      lambda: "ops",
      controller: "availability_slots",
      action: "update",
      auth: "cognito",
      tables: [:availability_slots, :employees, :pickups]
    },
    {
      verb: "DELETE",
      path: "/availability_slots/{availability_slot_id}",
      gateway: "ops",
      lambda: "ops",
      controller: "availability_slots",
      action: "destroy",
      auth: "cognito",
      tables: [:availability_slots, :employees, :pickups]
    },
    {
      verb: "GET",
      path: "/bundles/{bundle_id}",
      gateway: "ops",
      lambda: "ops",
      controller: "bundles",
      action: "show",
      auth: "cognito",
      tables: [:inventory]
    },
    {
      verb: "PUT",
      path: "/bundles/{bundle_id}",
      gateway: "ops",
      lambda: "ops",
      controller: "bundles",
      action: "update",
      auth: "cognito",
      tables: [:inventory]
    },
    {
      verb: "DELETE",
      path: "/bundles/{bundle_id}",
      gateway: "ops",
      lambda: "ops",
      controller: "bundles",
      action: "destroy",
      auth: "cognito",
      tables: [:inventory]
    },
    {
      verb: "GET",
      path: "/connect_account/{customer_id}",
      gateway: "ops",
      lambda: "ops",
      controller: "connect_account",
      action: "show",
      auth: "cognito",
      tables: [:customers]
    },
    {
      verb: "POST",
      path: "/connect_account/{customer_id}",
      gateway: "ops",
      lambda: "ops",
      controller: "connect_account",
      action: "create",
      auth: "cognito",
      tables: [:customers]
    },
    {
      verb: "GET",
      path: "/containers/{container_id}",
      gateway: "ops",
      lambda: "ops",
      controller: "containers",
      action: "show",
      auth: "cognito",
      tables: [:containers, :inventory, :billing_events]
    },
    {
      verb: "PUT",
      path: "/containers/{container_id}",
      gateway: "ops",
      lambda: "ops",
      controller: "containers",
      action: "update",
      auth: "cognito",
      tables: [:containers, :inventory, :billing_events]
    },
    {
      verb: "DELETE",
      path: "/containers/{container_id}",
      gateway: "ops",
      lambda: "ops",
      controller: "containers",
      action: "destroy",
      auth: "cognito",
      tables: [:containers, :inventory, :billing_events]
    },
    {
      verb: "GET",
      path: "/customers/{customer_id}",
      gateway: "ops",
      lambda: "ops",
      controller: "customers",
      action: "show",
      auth: "cognito",
      tables: [:customers, :containers, :inventory, :availability_slots]
    },
    {
      verb: "PUT",
      path: "/customers/{customer_id}",
      gateway: "ops",
      lambda: "ops",
      controller: "customers",
      action: "update",
      auth: "cognito",
      tables: [:customers, :containers, :inventory, :availability_slots]
    },
    {
      verb: "DELETE",
      path: "/customers/{customer_id}",
      gateway: "ops",
      lambda: "ops",
      controller: "customers",
      action: "destroy",
      auth: "cognito",
      tables: [:customers, :containers, :inventory, :availability_slots]
    },
    {
      verb: "GET",
      path: "/employees/{employee_id}",
      gateway: "ops",
      lambda: "ops",
      controller: "employees",
      action: "show",
      auth: "cognito",
      tables: [:employees]
    },
    {
      verb: "PUT",
      path: "/employees/{employee_id}",
      gateway: "ops",
      lambda: "ops",
      controller: "employees",
      action: "update",
      auth: "cognito",
      tables: [:employees]
    },
    {
      verb: "DELETE",
      path: "/employees/{employee_id}",
      gateway: "ops",
      lambda: "ops",
      controller: "employees",
      action: "destroy",
      auth: "cognito",
      tables: [:employees]
    },
    {
      verb: "GET",
      path: "/inventory/{inventory_id}",
      gateway: "ops",
      lambda: "ops",
      controller: "inventory",
      action: "show",
      auth: "cognito",
      tables: [:inventory]
    },
    {
      verb: "GET",
      path: "/item_changes/{item_change_id}",
      gateway: "ops",
      lambda: "ops",
      controller: "item_changes",
      action: "show",
      auth: "cognito",
      tables: [:item_changes, :inventory]
    },
    {
      verb: "PUT",
      path: "/item_changes/{item_change_id}",
      gateway: "ops",
      lambda: "ops",
      controller: "item_changes",
      action: "update",
      auth: "cognito",
      tables: [:item_changes, :inventory]
    },
    {
      verb: "DELETE",
      path: "/item_changes/{item_change_id}",
      gateway: "ops",
      lambda: "ops",
      controller: "item_changes",
      action: "destroy",
      auth: "cognito",
      tables: [:item_changes, :inventory]
    },
    {
      verb: "GET",
      path: "/items/{item_id}",
      gateway: "ops",
      lambda: "ops",
      controller: "items",
      action: "show",
      auth: "cognito",
      tables: [:inventory, :serp_pricing_results]
    },
    {
      verb: "PUT",
      path: "/items/{item_id}",
      gateway: "ops",
      lambda: "ops",
      controller: "items",
      action: "update",
      auth: "cognito",
      tables: [:inventory, :serp_pricing_results]
    },
    {
      verb: "DELETE",
      path: "/items/{item_id}",
      gateway: "ops",
      lambda: "ops",
      controller: "items",
      action: "destroy",
      auth: "cognito",
      tables: [:inventory, :serp_pricing_results]
    },
    {
      verb: "GET",
      path: "/pickups/{pickup_id}",
      gateway: "ops",
      lambda: "ops",
      controller: "pickups",
      action: "show",
      auth: "cognito",
      tables: [:pickups, :customers]
    },
    {
      verb: "PUT",
      path: "/pickups/{pickup_id}",
      gateway: "ops",
      lambda: "ops",
      controller: "pickups",
      action: "update",
      auth: "cognito",
      tables: [:pickups, :customers]
    },
    {
      verb: "DELETE",
      path: "/pickups/{pickup_id}",
      gateway: "ops",
      lambda: "ops",
      controller: "pickups",
      action: "destroy",
      auth: "cognito",
      tables: [:pickups, :customers]
    },
    {
      verb: "GET",
      path: "/returns/{return_id}",
      gateway: "ops",
      lambda: "ops",
      controller: "returns",
      action: "show",
      auth: "cognito",
      tables: [:returns, :inventory, :customers]
    },
    {
      verb: "PUT",
      path: "/returns/{return_id}",
      gateway: "ops",
      lambda: "ops",
      controller: "returns",
      action: "update",
      auth: "cognito",
      tables: [:returns, :inventory, :customers]
    },
    {
      verb: "DELETE",
      path: "/returns/{return_id}",
      gateway: "ops",
      lambda: "ops",
      controller: "returns",
      action: "destroy",
      auth: "cognito",
      tables: [:returns, :inventory, :customers]
    },
    {
      verb: "GET",
      path: "/terms_acceptances/{terms_acceptance_id}",
      gateway: "ops",
      lambda: "ops",
      controller: "terms_acceptances",
      action: "show",
      auth: "cognito",
      tables: [:terms_acceptances]
    },
    {
      verb: "GET",
      path: "/customers/{customer_id}/items/{item_id}",
      gateway: "ops",
      lambda: "ops",
      controller: "customers/items",
      action: "show",
      auth: "cognito",
      tables: [:customers, :containers, :inventory, :availability_slots, :pickups]
    },
    {
      verb: "PUT",
      path: "/customers/{customer_id}/items/{item_id}",
      gateway: "ops",
      lambda: "ops",
      controller: "customers/items",
      action: "update",
      auth: "cognito",
      tables: [:customers, :containers, :inventory, :availability_slots, :pickups]
    },
    {
      verb: "DELETE",
      path: "/customers/{customer_id}/items/{item_id}",
      gateway: "ops",
      lambda: "ops",
      controller: "customers/items",
      action: "destroy",
      auth: "cognito",
      tables: [:customers, :containers, :inventory, :availability_slots, :pickups]
    },
    {
      verb: "PUT",
      path: "/items/{item_id}/listings/{listing_id}",
      gateway: "ops",
      lambda: "ops",
      controller: "items",
      action: "update_item_listing",
      auth: "cognito",
      tables: [:inventory, :serp_pricing_results, :item_listings]
    },
    {
      verb: "DELETE",
      path: "/items/{item_id}/listings/{listing_id}",
      gateway: "ops",
      lambda: "ops",
      controller: "items",
      action: "destroy_item_listing",
      auth: "cognito",
      tables: [:inventory, :serp_pricing_results, :item_listings, :sell_events]
    }
  ].freeze
end
