# frozen_string_literal: true

# Auto-generated by: ruby scripts/list_routes.rb --ruby-output payments
# Do not edit manually - regenerate with `scripts/list_routes.rb --ruby-output payments'

module Routes
  PAYMENTS = [
    {
      verb: "POST",
      path: "/checkout/create",
      gateway: "payments",
      lambda: "payments",
      controller: "checkout",
      action: "create",
      auth: "none",
      tables: [:cart, :inventory]
    },
    {
      verb: "GET",
      path: "/checkout/success",
      gateway: "payments",
      lambda: "payments",
      controller: "checkout",
      action: "success",
      auth: "none",
      tables: [:cart, :inventory]
    },
    {
      verb: "POST",
      path: "/webhook",
      gateway: "payments",
      lambda: "payments",
      controller: "stripe",
      action: "webhook",
      auth: "none",
      tables: [:customers, :action_logs, :inventory_items]
    }
  ].freeze
end
