# frozen_string_literal: true

# Auto-generated by: ruby scripts/list_routes.rb --ruby-output ses_events
# Do not edit manually - regenerate with `scripts/list_routes.rb --ruby-output ses_events'

module Routes
  SES_EVENTS = [
    {
      verb: "POST",
      path: "/bounce",
      gateway: "ses_events",
      lambda: "ses_events",
      controller: "ses_events",
      action: "bounce",
      auth: "none",
      tables: [:email_suppressions, :customers]
    },
    {
      verb: "POST",
      path: "/complaint",
      gateway: "ses_events",
      lambda: "ses_events",
      controller: "ses_events",
      action: "complaint",
      auth: "none",
      tables: [:email_suppressions, :customers]
    }
  ].freeze
end
