# frozen_string_literal: true

# Auto-generated by: ruby scripts/list_routes.rb --ruby-output terms
# Do not edit manually - regenerate with `scripts/list_routes.rb --ruby-output terms'

module Routes
  TERMS = [
    {
      verb: "GET",
      path: "/terms/current",
      gateway: "onboarding",
      lambda: "terms",
      controller: "terms",
      action: "current",
      auth: "none",
      tables: []
    }
  ].freeze
end
